FROM flink:1.18-scala_2.12-java11

USER root

RUN sed -i 's|http://ports.ubuntu.com/ubuntu-ports/|http://mirror.yandex.ru/ubuntu-ports/|g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        openjdk-11-jdk-headless \
        python3 \
        python3-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && jdk_home="$(dirname "$(dirname "$(readlink -f "$(which javac)")")")" \
    && ln -s "$jdk_home/include" /opt/java/openjdk/include \
    && rm -rf /var/lib/apt/lists/*

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN pip3 install --no-cache-dir apache-flink==1.18.1

USER flink
